import type { DifficultySpec } from './types';

export const DIFFICULTY_PRESETS: Record<string, DifficultySpec> = {
  Story: {
    id: 'Story',
    label: 'Story',
    rails: { dmgMult: 0.9, hpMult: 1.2, aiAgg: 0.8, reinforceTurns: [7, 14], btTickBudgetMs: 2.0 },
    learn: {
      enabled: false,
      alpha: 0,
      perBattleClamp: 0,
      perSeasonClamp: 0,
      exploration: 0,
      memoryWindow: 0,
      opponentBuckets: false,
      scenarioBuckets: false,
    },
    commander: { riskBias: -10, rallyCdBias: +1, feintChance: 0.0, syncWindow: 2 },
    description: 'Relaxed opponents, no learning.',
  },
  Static: {
    id: 'Static',
    label: 'Static (No Learning)',
    rails: { dmgMult: 1.0, hpMult: 1.0, aiAgg: 1.0, reinforceTurns: [7, 14], btTickBudgetMs: 3.0 },
    learn: {
      enabled: false,
      alpha: 0,
      perBattleClamp: 0,
      perSeasonClamp: 0,
      exploration: 0.05,
      memoryWindow: 0,
      opponentBuckets: false,
      scenarioBuckets: false,
    },
    commander: { riskBias: 0, rallyCdBias: 0, feintChance: 0.05, syncWindow: 3 },
    description: 'Fair, consistent AI; seeds drive variety.',
  },
  Normal: {
    id: 'Normal',
    label: 'Normal (Light Learning)',
    rails: { dmgMult: 1.0, hpMult: 1.0, aiAgg: 1.0, reinforceTurns: [7, 14], btTickBudgetMs: 3.0 },
    learn: {
      enabled: true,
      alpha: 0.08,
      perBattleClamp: 0.8,
      perSeasonClamp: 3,
      exploration: 0.08,
      memoryWindow: 6,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: +2, rallyCdBias: 0, feintChance: 0.08, syncWindow: 3 },
    description: 'Learns gently across a campaign.',
  },
  Adaptive: {
    id: 'Adaptive',
    label: 'Adaptive (Smart)',
    rails: { dmgMult: 1.05, hpMult: 1.0, aiAgg: 1.1, reinforceTurns: [6, 12], btTickBudgetMs: 3.5 },
    learn: {
      enabled: true,
      alpha: 0.12,
      perBattleClamp: 1.5,
      perSeasonClamp: 6,
      exploration: 0.12,
      memoryWindow: 10,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: +6, rallyCdBias: -1, feintChance: 0.15, syncWindow: 4 },
    description: 'Noticeably adapts to your habits.',
  },
  Hard: {
    id: 'Hard',
    label: 'Hard',
    rails: { dmgMult: 1.1, hpMult: 1.0, aiAgg: 1.1, reinforceTurns: [6, 12], btTickBudgetMs: 3.5 },
    learn: {
      enabled: true,
      alpha: 0.12,
      perBattleClamp: 1.2,
      perSeasonClamp: 5,
      exploration: 0.1,
      memoryWindow: 10,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: +4, rallyCdBias: -1, feintChance: 0.15, syncWindow: 4 },
    description: 'Tighter timings and faster adaptation.',
  },
  Brutal: {
    id: 'Brutal',
    label: 'Brutal (No Mercy)',
    rails: { dmgMult: 1.2, hpMult: 0.95, aiAgg: 1.2, reinforceTurns: [5, 10], btTickBudgetMs: 4.0 },
    learn: {
      enabled: true,
      alpha: 0.16,
      perBattleClamp: 2.0,
      perSeasonClamp: 8,
      exploration: 0.15,
      memoryWindow: 14,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: +10, rallyCdBias: -2, feintChance: 0.22, syncWindow: 5 },
    description: 'Aggressive; fast learning and surges.',
  },
  Director: {
    id: 'Director',
    label: 'Rival Director (World Learns)',
    rails: { dmgMult: 1.05, hpMult: 1.0, aiAgg: 1.15, reinforceTurns: [6, 12], btTickBudgetMs: 3.5 },
    learn: {
      enabled: true,
      alpha: 0.12,
      perBattleClamp: 1.2,
      perSeasonClamp: 5,
      exploration: 0.1,
      memoryWindow: 12,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: +4, rallyCdBias: 0, feintChance: 0.12, syncWindow: 4 },
    description: 'Strategic layer also adapts (routes, garrisons).',
  },
  Custom: {
    id: 'Custom',
    label: 'Custom',
    rails: { dmgMult: 1.0, hpMult: 1.0, aiAgg: 1.0, reinforceTurns: [7, 14], btTickBudgetMs: 3.0 },
    learn: {
      enabled: true,
      alpha: 0.1,
      perBattleClamp: 1.0,
      perSeasonClamp: 4,
      exploration: 0.1,
      memoryWindow: 8,
      opponentBuckets: true,
      scenarioBuckets: true,
    },
    commander: { riskBias: 0, rallyCdBias: 0, feintChance: 0.1, syncWindow: 3 },
    description: 'Player-tuned mix in Settings.',
  },
};
