
export * from './types';
export { createAIContext, simulateTick, simulateSeason } from './simulate';
export { seedRng, rngBool, rngInt, rngPick } from './rng';
export { planArmyOrders } from './military';
export { evaluateDiplomacy } from './diplomacy';
export { computeFactionScores } from './scoring';
export { snapshot, snapshotExtended, getPlayerOpportunities } from './devtools';
export { considerTradeTreaties, applyTreatyBonuses } from './diplomacy.treaties';
export { chooseSeasonalStances, setStance } from './military.stance';
export { spawnContraband, spawnSmugglers, moveSmugglers, rollSmugglerAmbush } from './economy.black';
export { computeFrontlines } from './frontline';
export { assignArmyObjectives, scoreObjectiveProgress } from './objectives';
export { proposePeaceDeal, acceptPeace, tickReparations } from './peace.variants';
export { rollSeasonalEconomyEvents } from './economy.events';
export { updateFactionMemory, recordEvent, getModifiedRelation } from './memory';
export { recomputeDepotRadius, applySupplyAttrition, getArmyMoraleMod, getArmySupplyMod } from './logistics';
export { rollWeatherGrid, applyWeatherModifiers, getRegionWeather } from './weather';
export { maybeStartPeaceConference, runPeaceConferences } from './peace.conference';
export { simulateLivingTick, livingWorldActive, LIVING_WORLD_ENABLED } from './integrations';
export { snapshotLivingWorld } from './devtools.living';
export { evolvePersonalities } from './personality';
export { updateReputation, getFactionDescriptor } from './reputation';
export { considerAlliances } from './alliances';
export { emotionalEvents } from './events.adaptive';
export { simulateAdaptiveTick } from './integrations';
export { snapshotAdaptive } from './devtools.adaptive';
